### PR TITLE
Solution to #1 in Go language

### PR DESCRIPTION
**Pull request by marshallKR7**
Question: https://github.com/opencode18/CodeStash/issues/1
Language used :Go
Link of code: https://code.hackerearth.com/8a9b4dg

### CODE REVIEW

**Comment by gauthamzz** [comment]
make it like a blog post.
with question and answer as well.

**Comment by marshallKR7** [comment]
Okk sir

**Comment by marshallKR7** [comment]
@gauthamzz  All other is fine but possibly due to the last jekyll release all of the quote characters in the markup got messed up and this is why special characters like &,"",/,< is showing somewhat different in the blog. So what should I do,make a PR?
I have made the blog btw.

**Comment by marshallKR7** [comment]
@gauthamzz I have made a blog for it and thus made a PR, can you review it or do i have to add or delete something?

**Comment by gauthamzz** [comment]
can you add this solition in maekdown and add in _posts

**Comment by marshallKR7** [comment]
Okk,though I have made one PR #11 but as now project it updated so I will make a new PR shortly. :D

**Comment by gauthamzz** [comment]
lgtm

**Pull request closed without merging**
