### PR TITLE
Made a blog for solution to question of Day 3

### PR DESCRIPTION
**Pull request by GOVINDDIXIT**
Question: opencode18/CodeStash#3
Link of code :  https://code.hackerearth.com/c2aa82u

### CODE REVIEW

**Comment by gauthamzz** [comment]
since you answeered first for question 3 rd day.

You can send pr for 3rd day. make in posts folder like a proper blog post

**Comment by namantw** [comment]
@gauthamzz I had submitted a PR for question 3 long ago please check PR no 7 I had also given the IDEONE link ☹️

**Comment by mubaris** [comment]
It should be a blog post

**Review by mubaris — CHANGES_REQUESTED** [review]
It should be a blog post

**Comment by GOVINDDIXIT** [comment]
Do I have to submit a blog post for solution 3 as I am confused someone has already submitted

**Comment by GOVINDDIXIT** [comment]
@gauthamzz   I have made the blog post of Day 3 question as demanded

**Review by mubaris — CHANGES_REQUESTED** [review]
files in `_posts` have a structure for filename

check that out

**Comment by GOVINDDIXIT** [comment]
@mubaris File name changed

**Comment by GOVINDDIXIT** [comment]
Do I will get points as it was said to me to form the blog post but i see someone had already posted without being assigned

**Comment by gauthamzz** [comment]
It’s not assigned . It’s fcfs in this repo .

**Pull request closed without merging**
